project:
  type: book
  output-dir: dist

lang: en
tbl-cap-location: top

book:
  title: nanoChrome
  subtitle: Subtitle

  author:
    - name: John Grümph
      url: https://legrumph.org
  date: 2015-09-30
  isbn: 979-10-95063-07-0
  abstract: Abstract
  output-file: nanoChrome
  description: Description

  search: true
  downloads: [pdf]
  
  repo-url: https://github.com/luminarious/nanoChrome
  repo-actions: [edit, source, issue]
  repo-branch: quarto

  chapters:
    - index.qmd
    - content/intro.qmd
    - content/cyberpunk.qmd
    - content/characters.qmd
    - content/rules.qmd
    - content/matrix.qmd
    - content/relationships.qmd
    - content/vehicles.qmd
    - content/running.qmd
    - content/adventures.qmd
    - content/enemies.qmd
    - content/magic.qmd
    - content/catalogues.qmd
  appendices: 
    - content/charsheet.qmd
    - content/license.qmd

format:
  html:
    theme: yeti
    css: assets/site.css
    toc: true
    reference-location: margin
    callout-appearance: simple
    number-sections: false
  pdf:
    number-sections: false
    toc: true
    css: assets/book.css
    pdf-engine: prince
    pdf-engine-opts:
      - -v
