# People of Chrome City

> "They're vampires, Cowboy. They suck the blood of the Earth because that's what keeps them alive, but they don't know what it is to live for."
>
> —Walter Jon Williams, Wired

nanoChrome offers you to play in a relatively coherent world. So don't try to balance the opposites, but put the right things in the right places and let the players be intrepid. If a place has to be guarded by a real army, so be it. If the gangers are really lousy, so much the better. Characters will alternately be prey and predator depending on what they want to accomplish.

Use the archetypes for each as needed, mixing a type, a profile and an equipment pack. You can add any skills and abilities you think make sense.

::: callout-note
It was the /Cs who gave nicknames to the norms, corresponding to their place in society. The terms have since passed into common parlance…
:::

## NPC archetypes

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-------+
| DESCRIPTION                                                                                                                                                                                                                                             | CHANCE | CONN. |
+:========================================================================================================================================================================================================================================================+=======:+======:+
| ZOMBIES are anyone who leads a perfectly normal life - metro, work, sleep. They hang out on public transport, roam the anarzone, forget themselves in corpos leather lounges or float in the persistent worlds of the matrix.                           | 0      | 1     |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-------+
| SKELETONS are the zombies who have a gun and a uniform. They are responsible for guarding the herd and preventing the deviants from chewing their cud in peace. But apart from that, they don't differ much from the previous ones.                     | 0      | 3     |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-------+
| GHOULS are enhanced zombies, who have understood that they can feed on the masses. They are all the neighbourhood bullies, the ambitious and sadistic corpos executives, the functional sociopaths who parasitise society.                              | 1      | 5     |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-------+
| VAMPIRES stand out from the crowd. They rule or give the illusion of ruling. They have great powers and very little responsibility, but they are not untouchable. Generally, they are ghouls who have risen from seed and hope to become liches.        | 3      | 10    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-------+
| LICHES are out of reach. They are the real masters of the world, the ones who decide for everyone. Unfortunately, they are sometimes so far away that they can no longer see the details and a few deviant zombies can still play nasty tricks on them. | 7      | 15    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-------+

## NPC profiles

| 1D6 | PROFILE      | POWER |  HP | DEFENCE |
|:---:|:-------------|------:|----:|--------:|
|  1  | HALF-SALT    |    +0 |   5 |       8 |
|  2  | BIG MAN      |    +1 |  10 |       9 |
|  3  | STRONG       |    +2 |  15 |      10 |
|  4  | BIG SHOT     |    +3 |  20 |      11 |
|  5  | BIG OX       |    +4 |  25 |      12 |
|  6  | WE SAY "SIR" |    +5 |  30 |      13 |

## NPC equipment

+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| D26    | ENEMY              | WEAPONS                                                                                                            | MODIFIERS       | CYBERNETICS                                                                                                                                                                                 |
+:======:+:===================+:===================================================================================================================+:================+:============================================================================================================================================================================================+
| 1.1    | CORPORATE AGENT    | FIST WEAPON \[attack +2; damage +1; Interfaced, Secure, Silent, Impact, Versatile multitool, Voice Multicharger\]\ | HP +10\         | NEURONIC \[Retinal display, Emotional control, Stress reducer, Wired reflexes\]\                                                                                                            |
|        |                    | CIVIL PROTECTION \[Interfaced, Discreet\]                                                                          | Defence +4\     | PANOPTIC \[Photographic memory, Light amplifier\],\                                                                                                                                         |
|        |                    |                                                                                                                    | Initiative +1d6 | REINFORCEMENTS \[Automatic stimulation, Double heart, Blood filter\]                                                                                                                        |
+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1.2    | CORPORATE GUARD    | MELEE WEAPON \[attack +2; damage +0; Accuracy, Discrete\]\                                                         | HP +0\          | NANOGENETIC \[Rejuvenation\]                                                                                                                                                                |
|        |                    | CIVIL PROTECTION \[Discrete\]                                                                                      | Defence +1\     |                                                                                                                                                                                             |
|        |                    |                                                                                                                    | Initiative +0   |                                                                                                                                                                                             |
+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1.3    | CORPORATE COMMANDO | ASSAULT RIFLE \[Attack +2; Damage +4; Interfaced, Secure, Impact, Multipurpose Chambering, Voice Multicharger\]\   | HP +20\         | NEURONIC \[Retinal display, Wired reflexes\]\                                                                                                                                               |
|        |                    | TACTICAL PROTECTION \[Reinforcements, IFF, Auto-injectors\].                                                       | Defence +6\     | PROSTHETIC \[Woven skin, Bone replacement, Nictitating membrane\]\                                                                                                                          |
|        |                    |                                                                                                                    | Initiative +1d6 | STRENGTHENING \[Automatic stimulation, Double heart\]                                                                                                                                       |
+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1.4    | CORPORATE CPA      | LONG NANOBLADE \[attack +4; damage +9; Impact, Accuracy, Interfaced\]\                                             | HP +0\          | NEURONIC \[Wired Reflexes\]\                                                                                                                                                                |
|        |                    | FIST WEAPON \[attack +4; damage +6; Impact, Interfaced\]                                                           | Defence +6\     | CPA \[Acceleration, Anti-shock, Armor, Armor x2, EMP Protection\]                                                                                                                           |
|        |                    |                                                                                                                    | Initiative +1d6 |                                                                                                                                                                                             |
+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1.5    | COMBAT CYBORG      | LONG NANOBLADE \[attack +4; damage +5; Impact, Accuracy, Interfaced\]                                              | HP +15\         | NEURONIQUE \[Inhibiteur de douleur, Réflexes câblés\]\                                                                                                                                      |
|        |                    |                                                                                                                    | Défense +4\     | NANOGÉNÉTIQUE \[Amortisseur traumatique, Modification endocrinienne, Pyrokynésie\]\                                                                                                         |
|        |                    |                                                                                                                    | initiative +1d6 | PANOPTIQUE \[Équilibre\]\                                                                                                                                                                   |
|        |                    |                                                                                                                    |                 | PROSTHÉTIQUE \[Peau tissée, Plaques dermiques, Sutures automatiques, Membres inférieurs, Amortisseurs de saut, Assistance cinétique, Membres supérieurs, Impacteurs, Remplacement osseux\]\ |
|        |                    |                                                                                                                    |                 | RENFORCEMENTS \[Double coeur\]                                                                                                                                                              |
+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1.6    | GANGER             | ASSAULT RIFLE \[attaque +2; dégâts +4; Précision, Impact\]                                                         | HP +0\          | —                                                                                                                                                                                           |
|        |                    |                                                                                                                    | Défense +0\     |                                                                                                                                                                                             |
|        |                    |                                                                                                                    | Initiative +0   |                                                                                                                                                                                             |
+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.1    | CORPORATE GUARD    | ASSAULT RIFLE \[attack +2; damage +4; Precision, Impact\]\                                                         | HP +0\          | PROSTHETICS \[Woven skin, dermal plates\]                                                                                                                                                   |
|        |                    | TACTICAL PROTECTION \[Reinforcements, IFF, Auto-injectors\]                                                        | Defense +6\     |                                                                                                                                                                                             |
|        |                    |                                                                                                                    | Initiative +0   |                                                                                                                                                                                             |
+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.2    | HENCHMAN           | HANDGUN \[attack +4; damage +0; Precision, Discreet, Interfaced\] CIVILIAN PROTECTION \[Discreet\]                 | HP +5\          | NEURONICS \[Wired reflexes\]\                                                                                                                                                               |
|        |                    |                                                                                                                    | Defense +4\     | NANOGENETICS \[Hydra genoblasts, Totipotent genoblasts\]                                                                                                                                    |
|        |                    |                                                                                                                    | Initiative +1d6 |                                                                                                                                                                                             |
+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.3    | FIELD JOURNALIST   | HANDGUN \[attack +2; damage +0; Precision, Discreet\]\                                                             | HP +0\          | PANOPTIC \[Sound editor, SSP recorder, Sensory implant, Photographic memory, Micro-cannon, Zoom, High-definition vision\]                                                                   |
|        |                    | CIVILIAN PROTECTION \[Discreet\]                                                                                   | Defense +2\     |                                                                                                                                                                                             |
|        |                    |                                                                                                                    | Initiative +0   |                                                                                                                                                                                             |
+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.4    | EVERYMAN           | —                                                                                                                  | HP +0\          | —                                                                                                                                                                                           |
|        |                    |                                                                                                                    | Defense +0\     |                                                                                                                                                                                             |
|        |                    |                                                                                                                    | Initiative +0   |                                                                                                                                                                                             |
+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.5    | CORPORATE OFFICER  | HANDGUN \[attack +4; damage +1; Precision, Interfaced, Secured\]\                                                  | HP +5\          | NEURONICS \[Retinal display, Emotion control, Stress reducer, Wired reflexes, Hidden memory, Logic processors\]\                                                                            |
|        |                    | CIVILIAN PROTECTION \[Interfaced, Discreet\]                                                                       | Defense +4\     | NANOGENETICS \[Rejuvenation, Hydra genoblasts, Totipotent genoblasts\]                                                                                                                      |
|        |                    |                                                                                                                    | Initiative +1d6 |                                                                                                                                                                                             |
+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.6    | STREETNINJA        | SHORT NANOBLADE \[attack +4; damage +1; Impact, Precision, Interfaced\]                                            | HP +0\          | NEURONICS \[Wired reflexes\]\                                                                                                                                                               |
|        |                    |                                                                                                                    | Defense +4\     | PROSTHETICS \[Woven skin, Thermo-optic camouflage, Dermal plates, Subdermal pocket, Thermal regulation, Flash-dermis\]                                                                      |
|        |                    |                                                                                                                    | Initiative +1d6 |                                                                                                                                                                                             |
+--------+--------------------+--------------------------------------------------------------------------------------------------------------------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
