# Relationships

> It was in sexual relationships that things things started to get strange, that I realised that I might not have the upper hand, shall we say, on this that I might not have control, shall we say, over what I might feel. I now knew everything that Elaine liked and everything that she didn't like. I wasn't trying anything different, nothing that would make me imagine that she was someone else or anything like that. It was more perverse than that. I just remember feeling that Elaine was wearing some kind of mask that night, a mask that she couldn't take off, and that the mask was her own face.
>
> —Jonathan Dee, The Factory of Illusions

Characters have one or more relationships (see page 80) and can spend their connection points to activate them, in order to get their help. You can, of course, modulate the spending of connection points according to the circumstances: have the characters helped the relationship lately or done it a favour? Is the service a little more or less important than expected, etc.? If the request is directly related to the services offered by the contact (see page 158), feel free to lower the price a notch.

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+---------+----------+
| RELATIONSHIP INTERVENTION                                                                                                                                                                             | Contacts | Friends | Intimate |
+:======================================================================================================================================================================================================+=========:+========:+=========:+
| A minor service, such as a trivial (but important) information important for the characters) or a material help that does not require effort.                                                         | 2        | 0       | 0        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+---------+----------+
| An important service, such as crucial information or time-consuming material help.                                                                                                                    | 5        | 2       | 0        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+---------+----------+
| A major service, which puts the relationship at odds with people they otherwise know.                                                                                                                 | 10       | 4       | 2        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+---------+----------+
| A unique service, which puts the relationship at great personal risk - whether it is providing strategic information or showing up in the field at the risk of exposing oneself to all one's enemies. | \-       | 8       | 5        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+---------+----------+

## Building relationships

Print and cut out the portraits of the extras at the end of this booklet.

When creating the group (see page 21), the leader divides these portraits among the players present. Each player eliminates a figure that he or she does not like, and then distributes his or her cards among his or her neighbours in order to repeat the elimination process. When each player has only two portraits left, the leader shuffles them and deals them out again.

The players then write down a trait for each portrait - it is best to use a post-it note. A line can be an adjective, an opinion, a complete sentence, a quote, etc. The idea is to characterise as best you can what the portrait inspires. When each picture has received a first trait, the players distribute the cards between their neighbours (one card to the right, one card to the left) and then define new traits for the figures they have chosen. new lines for the figures they have received.

When all portraits have received two strokes, they are placed in the middle of the table. The players take each figure one after the other and, together, give it a name, an occupation, a short story, psychological traits and the reason why the characters might know it. You can also associate between one and three services with him, specifying his areas of activity and intervention in a specific way, in order to link them to the activities of the characters (see the following table).

> It is very funny, before starting to define each relationship together, to mix up the post-it notes bearing the traits and reassign them at random. Very often, the players' choices are based very heavily on the appearance of the portrait. By mixing the post-it notes and therefore the proposed traits, we end up with things that are much more exciting, amusing and interesting, and that open up the perspectives even more.

The game leader can then complete these portraits on his own, on the spot or at rest, by developing a history of the relationship - its secrets, its motivations, its links with other extras, its allegiances to certain factions, its short or long term objectives, etc. He can then give the additional information that he wants to know about the relationship. He can then give the players any additional information he wishes or keep it to himself.

BLACK MARKET: The relationship can supply or sell materials to the characters - illicit materials, discounted prices, usually specialising in one or two specific areas, but the black market as a whole remains accessible.

ENTRANCES: The relationship has entrances to all the important places in the city and can lead you there - a backstage pass, a corporate luncheon, a meeting at the town hall…

INFORMATION: The relationship may provide information in one or more areas - it may be technical information or news about news about factions or neighbourhoods.

INTERVENTION: The relationship is ready to give you a hand in the field, even if it means getting a little dirty. The more dangerous it is, the more compensation it will demand, but it knows how to behave and knows a few useful tricks.

TRANSPORT: The relationship can transport characters from one point to another in various conditions, whether it is to go fast or to be discreet. It can also transport equipment, messages and cargo. It has, of course, specialities that influence its preparation or its prices.

MATRIX: The relationship works in the matrix from home - or a secure location. If you don't have a coder in the team or if you want to support them, the programmer can do the work remotely, unless you give them a more specific job.

FENCE: The relationship can buy back material from characters - weapons, vehicles, jewellery, credit card laundering, etc. Fences are rarely fussy, but they will pay more in areas they are good at and less in areas where their costs will rise quickly due to lack of quick and easy outlets.

REFUGE: The relationship can provide you with a safe haven for a variable amount of time, with all the comforts if you are wealthy enough and even medical facilities in case of major concern. As long as you are under his protection, no one will find you unless he betrays you.

CONNECTIONS: The relationship is a node in a complex and extensive social network. His job is to connect people with each other, either on his own or on request. If you want to meet a particular person, that's who you should go to.

ADVICE: The relationship is a mentor and protector for the characters.

## Spiel and eloquence

Role-playing is a dialectic game, even a maieutic one, since the entire table gives birth to a story that no one knows what it will be a priori. It is a game in which language, speech, plays a decisive role. This is not without its paradoxes. Indeed, one rarely expects a player playing the role of a knight armed to the teeth to know how to handle a sword and lead a horse into battle - he describes his attacks verbally and it is the dice that decide the final result. But what about when the action in play, such as chatting up a security guard, can also be an action around the table, with the player speaking through his character's mouth to bamboozle the guard, and thus performing the manoeuvre himself - the player is of course in charge of the content of the chat, but it is the character who is the medium in play: he is the one who has the body language, the ability to lie straight to his face, etc.

This is an extremely thorny issue that has occupied pages and pages of discussion since the origin of role-playing. Everyone has their own opinions, solutions and practices. In fact, there is one specific term, which sums up all these discussions: it is roleplay - and, of course, no one agrees on its exact definition but everyone uses it to describe their ideal way of playing.

It is not our intention to resolve these paradoxes or even to give a definitive opinion, just to draw your attention to a few concerns you may have in play and to sketch out some answers that you can take hold of.

### The Player and The Character

The first paradox of roleplay is that the player both directs and embodies his character. He directs it by indicating to the game leader all his actions; he embodies it by speaking through his mouth. In the first case, it is the character's abilities and the result of the dice that indicate how things are done; in the second case, it is often the player's own oratory abilities that count. But what if a shy or less articulate player wants to play a barrister capable of great oratory? What do you do when a player with a highly-developed oratory skills plays an illiterate bullhead who is unable to chat? Certainly not forbidding it; and you will probably find it very difficult to compensate for natural tendencies.

Nevertheless, there are several possibilities: the first is to listen first and foremost to the arguments put forward and not to the way they are said. Sometimes a simple, decisive word or phrase is enough to turn a discussion on its head; conversely, beware of tautology, bluster and obvious sophistry.

The second is to index the rolls (the character's abilities) to the roleplay (the player's words). Basically, if a player has glibness, take the difficulty of the rolls down a notch - a good player can eventually make up for his character's crass incompetence, but that won't do it. And don't forget that a simple argument at the right moment sometimes counts for more than a very impressive one-man show.

### Nature of social conflict

Where it gets tricky is that not all social situations are equal in terms of storytelling, and not all have the same stakes. The situations are extremely varied - from buying something on the black market to a 'legal' tussle in front of a yakuza oyabun, with the risk of having one's little finger rolled in the sand, if not one's head.

### Go fast, don't play everything

Not every situation is worth five minutes of show and tell that will involve one or two players and leave the rest idle. Bribing a guard to get into the museum just before closing time, convincing the intern at the hotel desk to show you the bad guy's room, or getting hired as a bodyguard to watch over the backstage area of a mega-concert only requires a quick roll and sometimes no roll at all. These are actions that just indicate the direction the story is taking: you either get into the museum or not, you either get the location of the room or not, you either get hired or not. Of course, if you're having fun, play the whole scene - sometimes that's even the best thing to do (we told you it was sometimes paradoxical) - but frankly, don't waste time.

### Small talk

At the other end of the spectrum are all the exchanges that absolutely must be played in full to achieve their purpose: what information is actually being dropped by each party? What do we learn from a slip of the tongue or a clever innuendo? What do they reveal that they wanted to keep secret? These informal conversations have an unparalleled evocative power - the impression for the players that the world is truly alive, deep. Nevertheless, the game leader has to pay attention to several things: What does the person he is playing know and what does he not know during the conversation? What are his personal objectives, his fears, his desires, the means of compelling or seducing him? What is his real social power, his networks, his supports, his safeguards, his own means of pressure or seduction? What does he know about the characters and how does he view them? As dangerous adversaries? As mere transients who can take the blame for his own misdeeds? Likely allies whom it is good policy to support for the moment? During these conversations, feel free to put the rest of the world on stage around them - the servants coming and going, the children and family bustling about nearby, the staff taking notes and nodding knowingly, the little glances exchanged backstage, etc.

### Between dog and wolf

There are still circumstances in which the conversation and the throw are equally important. Here you have to find the right balance. There are no precise rules like those of combat to manage social conflicts which must decide between two speakers - first and foremost because the player's word counts and he will never be satisfied with a "And now it's my turn to throw my argument in his face, 7 points of damage with the sarcastic smile bonus!

So how do you do it? You can manage everything in a Charisma roll, with a variable bonus or malus depending on the social or political position of each party, on the arguments put forward, on the weapons present, on the number of allies in the room, etc. You can make several rolls - the best of three or five rounds, for example. You can bring in outside referees - an influential corporatist, an ambitious gang leader, a well-connected cop - who listen to no one and push their own agenda. Use white and black tokens to count the arguments. Involve the crowd. Ask someone from outside the game table to sit in on the discussion and make a decision.

There is no single solution because there is no single social situation. Where combat always involves the use of weapons and well-defined physical tactical objectives, social conflict is highly subjective and therefore subject to all kinds of arbitration - so the game leader must always consider whether or not an extra is sensitive to arguments without stopping to consider whether or not he or she, as an individual, is sensitive to them.
