# Rules of the game

> We started IFT to change the world. Our suits are much better tailored today, our spirits finer. We've changed, but the world is still the same. If we don't do anything, someone else will.
>
> —Nathan Ingram, Person of Interest, S02E14

## The Golden Rule

Sometimes the playmaker doesn't know or doesn't want to answer a question - Is the corporate executive at his desk right now? Is there any ammunition left in the storeroom? Did the fire in their squat destroy the characters' equipment? Does the corporate security officer in pursuit recognise the characters in the lobby of the skyscraper?

Whenever you are faced with a question that may be important for the rest of the adventure, but whose answer is not directly relevant to you, roll 1d6. On a result of 4 or more, the answer to the question is yes. On a result of 3 or less, the answer is no.

Note: a triple-6 on the dice is always a success and earns one point of luck. A triple-1 is always a failure and yields not only one point of luck but also a bunch of extra complications!

## Roll the dice

To play, you need 3d6, one of which is a different colour from the others.

When you want to achieve a goal and something or someone gets in the way, roll the 3d6, add up the results and add the rank of an appropriate characteristic - for example Dexterity to blow out a lock with a knife blade or Wisdom to locate the drug stash under a floorboard. Don't forget any bonuses - such as a skill bonus.

To succeed, the total must be equal to or greater than a difficulty or an opposing roll made by an opponent or competitor who does not want you to succeed - in which case they roll 3d6 + Attribute (see page 295) and the results are compared. For a fixed difficulty, see the following table:

| Target number | Difficulty          |
|--------------:|:--------------------|
|             9 | Simple              |
|            12 | Difficult           |
|            15 | Difficult           |
|            18 | Very hard           |
|            21 | Extremely difficult |
|            24 | Almost impossible   |

### The delicate art of dice rolling

The principle of a roll is to confront a character's abilities with the possibility that they may fail to achieve their goals; the purpose of the roll is certainly not to punish them or prevent them from moving forward, but only to tell how the story is progressing. If it is a success, then the character succeeds and the story moves in the direction he wants; on a failure, the story takes an unexpected turn. And we continue to move forward: the player indicates what his character does in the new circumstances and the leader determines how it happens, with a description, a choice to be made and possibly a new dice roll.

#### The dice are useless…

If there is nothing in the character's way, or if it doesn't matter, there is no need to roll - it is automatically successful. And, of course, if the task is simply impossible to accomplish, it is automatically failed. More generally, if you don't have a good reason to invoke a random bifurcation of history, don't ask for a roll - ideally, you should have at least a vague idea of the different legs of the trousers of time that you might put on depending on the circumstances.

#### …yet you can't do without them

If something or someone complicates the task, opposes the character, or makes things very complicated, you have to roll the dice. The game leader must then assess the difficulty: there are two schools of thought.

a)  The first is to choose an objective difficulty. The action is more or less difficult because the circumstances or the task itself require it: try to imagine the scene, compare the action to your own knowledge or to what you have seen in films or read in novels. Generally, the more technical the task, the more circumstances beyond the control of a single human beast, the more random the general conditions, the more difficult it is.

b)  The second school is to determine the difficulty in terms of the story. If the task can change the story and the world profoundly, then the difficulty is huge; if it's just an incidental and peripheral perk, then the difficulty is ridiculous. It's a hair more complicated to deal with and anything but objective - plus, players can quickly realise that a difficulty of 24 to tail an extra in a trendy nightclub indicates that he's a super-important big bad next!

And, of course, you can happily mix and match approaches depending on when you play. The important thing is to be consistent with yourself, the world and the story.

### The secret ingredient

You know how to manage the difficulty of an action in an opposition - for example, two characters racing. In this case, the difficulty of the roll is the opponent's roll (3d6 + Power for an extra). What's to stop you doing the same for a static difficulty: instead of saying "it's a 15 difficulty", the difficulty to pick the lock is then equal to 3d6 + 4. Maybe the lock is a hair easier or a hair harder than you expected. This is handy when you don't know what to do or want to go fast. Just assume that chaos will make the decision for you…

### Ensure the show

Once the roll has been made, it's time to announce the consequences. If it's a success, the character achieves his immediate goal, as the player might expect under the best of circumstances. If the roll is really good - a result well above the difficulty, at least a five or six point margin - add a matrix effect: the character runs around bouncing off obstacles and street furniture while chasing a bad guy; the computer quickly spits out all the info it can and gives access to hidden backdoors to go even further; the checkpoint passage is so smooth that the character is suddenly the most innocent guy in the world. Give them a little advantage in this form: it's time saved, it's stealth, it's downright impressed witnesses, it's extra ¥, it's clues or additional information, etc.

### Ensure that the game continues

What if it fails? The biggest danger you face then is driving your story into a dead end. The character aims for a goal and misses it: now what? If it's just "no", the story can't develop. So it is very important that you see all failures not as a punishment, but as an opportunity, a way to bounce back and offer unexpected developments. Also, be careful that a failure is not immediately forgotten: there is nothing more frustrating than attempting an action that serves no purpose, even and especially by failing - as a feeling of uselessness and futility for the player.

How do you do it? The quickest way is to grant a success but demand something in return: the character gets hurt, compromises himself, loses time, material, money, has to agree to do a service, etc. Be imaginative and hit where you feel the player will cringe. Very important: the player can always choose to fail so that they don't have to agree to pay to succeed! The easiest way to do this is often to tap into resources: lose life points, luck points, connection points, etc. But it is always more interesting to find original ideas. In reality, the purpose of such an exchange is to push the player to choose between the plague and the cholera: succeed with a cost or simply fail? Don't make it too simple, but demand a quick answer.

The second way is to take advantage of a failure to complicate things and put new obstacles in the character's way. Not a wall, but a closed door. Not a bottomless precipice, but an unstable ledge from which it is difficult to escape. Not a cut bridge, but a long diversions. Not the loss of all one's money, but debts that must be repaid one day. Not an outright capture, but a price on your head. In short, continue to ruin the character's life and prevent him from seeing the sun. Accumulate the problems.

Or, more foolishly, require the player to play with his brain and find alternative and more subtle solutions…

### Describe, there will always be something left

One of the best ways to always have something to say to bounce back from a failure or bring in new twists is to describe the scenes all over the place! Think of sights, sounds, smells, textures, weather, materials, the shape of places, decorative details, lights and shadows - anything you can think of. Not only does this immerse the players in the appropriate atmosphere and give them plenty of relevant (or irrelevant) information to make decisions and describe the actions of their characters, but it's also great for giving you, the player, a head start. Use your own descriptions, on the fly, to create play and set up the twists and turns the dice are designed to provide.

## Cooperation

When one character helps another, he gives them a +1 bonus to their roll.

When the whole group must perform the same action - climbing a wall or advancing discreetly - the characters all seem to succeed if at least half of them succeed in their roll.

## Saves

In the course of adventures, your adventurer will certainly find himself in delicate and dangerous situations, facing multiple dangers: fire, falls, diseases, poisons, traps, etc.

A saving throw is a characteristic throw requested by the game leader to check whether the character manages to protect himself, at least in part, from a sudden danger or a vital threat. It is always a reaction and not something that comes from the character's will (even when the character has voluntarily swallowed the contents of a bottle of poison). The characteristic used depends on the type of danger and there are a few skills that should help you.

The difficulty depends on the circumstances, but mostly on what the player wants to achieve:

-   Easy or hard (9/12): you want to scare them.
-   Difficult to hard (15/18): you want to tap into the characters’ resources to weaken them.
-   Complicated or impossible (21/24): you ask for a saving throw to make the characters think they have a chance, but in fact they don't. It's not expected that they'll make it (even if there are some pleasant surprises).

If the character fails the roll, the effects of the danger apply. If he succeeds, the effects may be completely nullified or only limited (he does not die on the spot, but still suffers damage or injury, for example).

There are far too many possible hazards to list - from electric fences to terrifying corporate interface lockout programs, from combat gases to sudden explosions. Just try to think about the maximum consequences of the hazard (injury, death, unconsciousness, damage, etc.) and what can happen if the character succeeds in the saving throw.

## Combat

Action and Manoeuvre - Combat is turn-based - each opponent can perform an action (cast a spell, make an attack, use a skill) and a manoeuvre (move a few metres, take cover, aim, charge, help an ally, etc.). - A manoeuvre used in support of an action brings a +1 bonus to the action). It is always possible to use an action to perform a manoeuvre, but never vice versa.

Movement: if you need to calculate the exact distance a character has moved during a turn, ask for a Strength (all power) or Dexterity (all flexibility) roll. The result directly indicates the distance in metres.

Initiative - Once at the start of a fight, all combatants can make an Intelligence roll (or Power roll for extras) to determine the order of the action, from highest initiative to lowest. If, at any time, your initiative is 20 or more, you gain an extra action at the end of the turn (at your initiative minus 20). If one group surprises another, all members of the group get a +1d6 bonus to initiative.

> If you don't want the players to see the transition between the story being told informally and the start of a fight, don't say anything and roll the initiative in secret. Then simply distribute the word. Ideally, you should get the initiative bonus for each character and make several draws in advance, before the game starts. Then you simply refer to your notes when you need them. Don't forget to note the initiative increases and decreases due to feats and risks.

Attacks and damage - The difficulty of an attack roll is equal to your opponent's defence. If you hit, the damage is equal to the value of the different coloured die + your Strength or Dexterity rank, depending on the weapon you are using (melee or ranged). The damage is subtracted from the target's hit points. The coloured die is always an explosive die for calculating damage: if you roll a 6, roll the die again and add the new result. Continue as long as you get 6's. You can always distribute the damage to one or more opponents whose defence is equal to or less than that of the main target.

Special rules: there are dozens of specific cases that can arise in combat - whether the opponent is under cover or not, whether it is possible to disengage without taking a hit, whether it is possible to block a path so that only one opponent at a time can attack, whether I can shoot into the fray while my companions are engaged in fierce hand-to-hand combat, etc. In fact, every battle should bring up new issues and new tactics. But it is impossible (and pointless) to list them all and give a specific rule for each. In truth, this is the fundamental job of the game leader, the moment when he must fully assume his role: to referee, to make decisions, to use the golden rule, to make the players happy or on the contrary to increase the difficulties. If you make a bad decision once, it means you will make two very good ones later - so don't worry. The rules are simple enough that you have nothing to worry about. Trust your common sense and just follow the directions given to you by the story and the adventure.

### Feats and Risks

Each round of combat, you can choose a feat. The host rolls the risk you take in exchange… If a risk seems directly opposite to the feat you are choosing, ignore the risk and apply the feat.

+--------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FEAT                                                                                                         | 1D6       | RISK                                                                                                                                                                                   |
+:=============================================================================================================+:=========:+:=======================================================================================================================================================================================+
| VIOLENT HIT: You add 1d6 to your physical damage. This damage is non-explosive and does not apply to spells. | 1         | DEFLECTED HIT: You do not count the coloured die in your damage, only the applicable modifiers, or (at your discretion) you take damage yourself equal to the smallest die you rolled. |
+--------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PRECISE STRIKE: You seek to break through the opponent's armour.<br>You have a +2 bonus to attack.           | 2         | DISADVANTAGE: You have a -2 malus to attack or you lose a connection point.                                                                                                            |
+--------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CASCADE: You perform an additional manoeuvre at the same time as your action.                                | 3         | BLUNDER: If you fail your attack, things get very complicated: you lose your weapon, you fall, etc.                                                                                    |
+--------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CAUTION: You are careful. You have a bonus of +1 in defence for the turn.                                    | 4         | HAZARD: You are not paying attention. You have -1 in defence for the turn.                                                                                                             |
+--------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| VIVACITY: You gain 1d6 initiative points.                                                                    | 5         | DELAY: You lose 1d6 initiative points.                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TACTICS: You give a +2 bonus to one of your companions.                                                      | 6         | NONE: You are not hindered this turn and your feat applies without compensation.                                                                                                       |
+--------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### Staging a fight

Here are some tips to help you stage a fight (or a physical chase-type conflict).

#### General process

By following these steps, you should be fine in all situations.

1.  On his own initiative, the player indicates what he wants to do according to the situation and his tactical options. Everything is possible and he should not let himself be limited by technique. Eventually, he can choose a feat.
2.  The leader chooses the most appropriate way to handle what the player is asking for. This may be a characteristic roll (the most common is the attack roll, for example) or a simple description. You should not be impressed by even the strangest requests. For example, let's say the character wants to push an enemy away with his shoulder and throw him through a window - it's not written in black and white in the rules, but you can consider it a Strength roll. The damage rolled on the coloured die (with the Strength bonus) is not actually inflicted, but can be compared, for example, to the sum of the enemy's hit points and those of the window. If they are higher, the window shatters and the man falls through - and if they are lower, ask the victim for a saving throw! In fact, everything can be solved in a very simple way - whether it's disarming an opponent or shoving them into a hole, with attack rolls against the defence. Is the character making a feint to divert attention? Use Charisma to attack. He wants to drive his opponent over a weak floor? Use Intelligence to attack. Damage is a general indication of the effect of the attack - which you can turn into a difficulty for a saving throw quite simply (for example, with a difficulty of 7 + damage).
3.  The player rolls if necessary.
4.  The leader describes the consequences, says what happens, deals damage if necessary or bounces the action. Then he passes to the next player. Of course, this is exactly the same process for the characters' opponents (but the leader is on his own to decide things).

#### Three important points of combat

##### I. Stakes:

A fight is not something you engage in to pass the time. It is a high point in the story - the characters will risk their resources or their lives, perhaps worse. Even their opponents take the matter very seriously - after all, they are likely to lose their lives. In fact, in most situations, one does not go into battle without strong needs or clear objectives. In some cases, it is the characters who will have to define these objectives; in other cases, they will simply defend themselves against opponents who themselves have goals to achieve. The important point is to always ask what is at stake in a fight: why are we fighting? Do we have to go as far as the physical elimination of the opponent? Is it not enough to wound, stun, chase, intimidate or coerce? What if the enemy flees? Do you chase them to the finish or are you magnanimous? Fighting in a role-playing game is then also a lesson in humanity… Conversely, what do the characters risk? What are they willing to risk? It's pretty obvious that they will be victorious most of the time, after all aren't they the heroes of the story… But to win without glory is to triumph without danger (or something like that). Also, a fight must be able to cost: time, allies, wounds, equipment, information, reputation… The players know, deep down, that the death of their character is not a real possibility as they have so many ways to get out of it (by spending luck points or simply because they are not alone). Also, it is very important that other elements emerge that make the fight "dangerous" for their mission or adventure: most of the time, it is about seeing their objective escape. Also, play their opponents intelligently: they are not cannon fodder who die stupidly. If the characters want something, their enemies will do whatever it takes to get it out of their hands, and sometimes that means dodging the fight, running away or creating diversions.

##### II. Descriptions:

A fight is first of all a series of important choices grouped together in a very short period of time. There is an objective to fulfil and you have to do everything (or almost everything) to achieve it - free prisoners, steal or break an object, get through a defended area, flee in good order. It's rarely a case of slaughtering all your enemies, but rather a specific target. To make these choices, you need to be informed and it is the job of the game leader to inform his players: describe the terrain, the circumstances, the actions, the reactions, the twists and turns, the audience, the surprises, the equipment, the physical and emotional state of the opponents, etc. In fact, the more detail you can provide, the easier it will be to manage the actions of the characters (the little 2 and 4 above) and the easier it will be for the players to make decisions quickly (the little 1 above). This doesn't mean going off on a tangent or being fussy, just giving all the relevant tactical information. Two last important points: on the one hand, the players must be told, in a clear and unambiguous way, "You can win this fight" or "Run away, you fools! The players can't guess whether the opposition they are facing is up to them or not. You need to send clear and unambiguous messages, without telling them head-on (which would pull them out of the immersion). This means using appropriate descriptions and multiple clues, including alternative ways out. On the other hand, the players must be able to participate in the descriptions and thus establish facts that are verified. Before an ambush, for example, if they ask what the terrain is like, ask them to tell you what they want it to be like: after all, they are the ones setting up the ambush and therefore they are the ones choosing the location. And then, in the course of the fight, they can find places to hide, to slip away, to corner the opponent. Let them announce that they are hiding behind a table that didn't exist a few moments before - in truth, nobody paid any attention to it. Now you too can use this table in the descriptions.

##### III. Pacing:

Try to keep the flow of speech relatively even. This sometimes means cutting off a character's action, on a cliffhanger, to focus on another part of the battlefield and another character. Push your players to react quickly, to pass the word, to listen to each other - there's nothing worse than a player who looks up in the middle of a fight and says "Yeah, wait, here, go ahead, tell me again what's going on, where am I?" There's no point in punishing stupid actions or unfortunate initiatives. But inattention can be worth losing your turn! On your side, be careful not to push your players into inattention because you are spending too much time on a technicality or reviewing your notes or the rules. Make decisions when you don't know. At worst, roll the golden rule die. No one will replay the game or judge your refereeing mistakes; and if you think you've misjudged a situation or wronged a character, you'll make up for it the next time (by giving them a small bonus or a point of luck back). Pacing is also about technique. Have clear notes in front of you, with the life points, defence and initiative of the opponents; also, draw a square representing the game table. Arrange the names of the characters in the place of their players, and indicate their defence and initiative. When you hand out the floor, call out the players by their character's name. Make quick rolls for the opponents, compare to the defence, announce the result and how the conflict continues. A solid organisation of your post-it notes and numbers can help you speed up the manoeuvre. Ah. Still, a tip not to be overlooked: just as you write down the names of the characters so you only use those and not the players', write down the names or descriptions of the opponents - the Little Fat Guy, the Big Skinny Guy, the Scarfed Guy, Studded Armour, Big Hair, Big Mouth, etc. This will help you to immerse your players. On the other hand, if you're not going to tell your players that the strange shadow that's attacking them is The Priest, a techno-villain who's behind a spate of horrific murders, don't write down The Priest, just Strange Shadow. Because if you don't, there will always be a moment when, after reading the paper, you'll spill the beans and your players will look at you with a big smile: "Ah, of course it's The Priest! The guy we've been looking for everywhere!"
